**importing pandas, numpy, matplotlib and seaborn**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**mouting using drive**

In [ ]:
df = pd.read_csv("survey_student.csv")
df.columns =["Date","Gender","Grade","Year","Faculty","Average","Accomodation","Monthly_Allowance","Scholarship_Bulsary","Study_Hours","Party_Socializing","Drinks_Consumed","Class_Missed","Modules_Failed","Romantic_Relationship","Alcohol_Consumption_Allowed","Relationship_Parents"]
df.sample(10)

,Date,Gender,Grade,Year,Faculty,Average,Accomodation,Monthly_Allowance,Scholarship_Bulsary,Study_Hours,Party_Socializing,Drinks_Consumed,Class_Missed,Modules_Failed,Romantic_Relationship,Alcohol_Consumption_Allowed,Relationship_Parents
111,2024/03/07 6:04:29 pm EET,Female,73.0,2nd Year,Economic & Management Sciences,62.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,No,8+,2,5-Mar,1,2,Yes,Yes,Very close
153,2024/03/07 6:59:23 pm EET,Female,85.0,NaN,Arts & Social Sciences,NaN,NaN,NaN,No,3-Jan,1,5-Mar,0,0,No,No,Close
351,2024/03/10 2:48:41 pm EET,Female,76.0,NaN,Economic & Management Sciences,60.0,NaN,R 7001 - R 8000,No,5-Mar,3,5-Mar,2,0,Yes,Yes,Close
303,2024/03/08 9:50:48 am EET,Male,67.0,1st Year,Economic & Management Sciences,30.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-Jan,4+,8+,4+,4+,No,Yes,Very close
24,2024/03/07 5:16:35 pm EET,Female,78.0,1st Year,Economic & Management Sciences,76.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,8+,2,5-Mar,2,0,No,Yes,Very close
387,2024/03/11 3:12:20 pm EET,Female,86.0,1st Year,Science,71.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,1,0,0,0,Yes,Yes,Very close
226,2024/03/07 9:27:52 pm EET,Female,82.0,2nd Year,Economic & Management Sciences,72.0,Private accommodation/ stay with family/friends,R 5001 - R 6000,No,5-Mar,3,3-Jan,0,0,No,Yes,Close
220,2024/03/07 9:14:34 pm EET,Female,78.0,2nd Year,Economic & Management Sciences,64.0,Private accommodation/ stay with family/friends,R 5001 - R 6000,No,8-May,2,8-May,4+,4+,Yes,Yes,Very close
138,2024/03/07 6:26:53 pm EET,Male,70.0,Postgraduate,AgriSciences,68.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-Jan,3,5-Mar,2,0,No,Yes,Very close
340,2024/03/09 9:53:21 am EET,Male,76.0,1st Year,Economic & Management Sciences,70.0,Private accommodation/ stay with family/friends,NaN,No,3-Jan,3,8+,2,0,Yes,No,Very close

# **Removing unnecessary columns**

**Dropping unnecessary columns**

In [4]:
df.drop(columns = ["Party_Socializing","Drinks_Consumed","Romantic_Relationship","Alcohol_Consumption_Allowed","Relationship_Parents"],inplace = True)

In [5]:
df.columns

Index(['Date', 'Gender', 'Grade', 'Year', 'Faculty', 'Average', 'Accomodation',
       'Monthly_Allowance', 'Scholarship_Bulsary', 'Study_Hours',
       'Class_Missed', 'Modules_Failed'],
      dtype='object')

**Checking the dtypes of each columns**

In [6]:
df.dtypes

Date                    object
Gender                  object
Grade                  float64
Year                    object
Faculty                 object
Average                float64
Accomodation            object
Monthly_Allowance       object
Scholarship_Bulsary     object
Study_Hours             object
Class_Missed            object
Modules_Failed          object
dtype: object

**Converting the Datetime into date only**

In [7]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

df["Year"] = df["Date"].dt.year

df.Year.sample(5)

/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:12:01 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:12:08 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:12:25 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:12:28 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:00 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:18 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:22 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:26 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:28 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:13:35 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:04 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:06 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:08 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:10 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:35 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:43 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:50 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:14:51 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:15:05 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:15:08 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:15:13 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:15:43 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:15:47 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:16:06 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:16:35 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:16:56 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:17:06 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:17:09 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:17:22 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:17:28 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:17:39 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:18:18 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:18:41 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:18:56 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:19:16 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:19:55 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:19:56 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:04 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:31 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:48 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:52 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:55 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:20:57 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:21:41 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:13 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:34 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:36 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:40 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:44 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:22:59 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
/tmp/ipykernel_20384/4168586279.py:1: FutureWarning: Parsed string "2024/03/07 5:23:11 pm EET" included an un-recognized timezone "EET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

388    2024
281    2024
10     2024
394    2024
17     2024
Name: Year, dtype: int32

**Dropping Date column**

In [8]:
df.drop(columns = ["Date"],inplace = True)
df.columns

Index(['Gender', 'Grade', 'Year', 'Faculty', 'Average', 'Accomodation',
       'Monthly_Allowance', 'Scholarship_Bulsary', 'Study_Hours',
       'Class_Missed', 'Modules_Failed'],
      dtype='object')

# **Handling Null Values**

**Checking null values**

In [9]:
df.isna().sum()

Gender                  2
Grade                   7
Year                    0
Faculty                 7
Average                86
Accomodation           23
Monthly_Allowance      31
Scholarship_Bulsary     8
Study_Hours             3
Class_Missed            3
Modules_Failed          3
dtype: int64

**Filling null values of Gender using Mode**

In [10]:
df.Gender.fillna(df["Gender"].mode()[0],inplace = True)

/tmp/ipykernel_20384/2490187954.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Gender.fillna(df["Gender"].mode()[0],inplace = True)

**Filling null values of Grade**

In [11]:
df.Grade.fillna(df["Grade"].mean(),inplace = True)

/tmp/ipykernel_20384/1817325729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Grade.fillna(df["Grade"].mean(),inplace = True)

**Filling null values of Faculty**

In [12]:
df.Faculty.fillna(df["Faculty"].mode()[0],inplace = True)

/tmp/ipykernel_20384/819885497.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Faculty.fillna(df["Faculty"].mode()[0],inplace = True)

**Counting different or unique values of accomodation and filling with mode**

In [13]:
df.Accomodation.value_counts()

Accomodation
Private accommodation/ stay with family/friends    335
Non-private accommodation ie. Res                   48
Name: count, dtype: int64

In [14]:
df.Accomodation.fillna(df["Accomodation"].mode()[0],inplace = True)

/tmp/ipykernel_20384/2965411295.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Accomodation.fillna(df["Accomodation"].mode()[0],inplace = True)

**Filling monthly allowance**

In [15]:
df.Monthly_Allowance.unique()

array(['R 4001- R 5000', 'R 7001 - R 8000', 'R 6001 - R 7000',
       'R 5001 - R 6000', nan, 'R 8000+'], dtype=object)

In [16]:
df.Monthly_Allowance.fillna(df["Monthly_Allowance"].mode()[0],inplace =True)

/tmp/ipykernel_20384/4167491968.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Monthly_Allowance.fillna(df["Monthly_Allowance"].mode()[0],inplace =True)

**Filling Scholarship and Bulsary**

In [17]:
df.Scholarship_Bulsary.value_counts()

Scholarship_Bulsary
No                     352
Yes (NSFAS, etc...)     46
Name: count, dtype: int64

In [18]:
df.Scholarship_Bulsary.fillna(df["Scholarship_Bulsary"].mode()[0],inplace = True)

/tmp/ipykernel_20384/620545314.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Scholarship_Bulsary.fillna(df["Scholarship_Bulsary"].mode()[0],inplace = True)

**Filling na of Study_Hours**

In [19]:
df.Study_Hours.value_counts()

Study_Hours
8+       114
5-Mar    105
3-Jan     83
8-May     81
0         20
Name: count, dtype: int64

In [20]:
df["Study_Hours"] = df["Study_Hours"].fillna(df["Study_Hours"].mode()[0])

**Handling Class missed**

In [21]:
df.Class_Missed.value_counts()

Class_Missed
0     214
1      75
2      63
4+     27
3      24
Name: count, dtype: int64

In [22]:
df.Class_Missed.fillna(df["Class_Missed"].mode()[0],inplace=True)

/tmp/ipykernel_20384/2756158103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Class_Missed.fillna(df["Class_Missed"].mode()[0],inplace=True)

**Handling Modules_Failed**

In [23]:
df.Modules_Failed.value_counts()

Modules_Failed
0     263
1      58
2      31
4+     27
3      24
Name: count, dtype: int64

In [24]:
df.Modules_Failed.fillna(df["Modules_Failed"].mode()[0],inplace = True)

/tmp/ipykernel_20384/2628923908.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Modules_Failed.fillna(df["Modules_Failed"].mode()[0],inplace = True)

# **Handling Outliers**

In [25]:
numeric_columns = df.select_dtypes(include = ["int32","float64"]).columns

In [26]:
for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    count = ((df[col] < lower_limit) | (df[col] > upper_limit)).sum()
    print(f"{col}: {count} outliers")

Grade: 8 outliers
Year: 0 outliers
Average: 2 outliers

**Using log(1 + x) to handle outliers**

In [27]:
df[["Grade","Average"]] = np.log1p(df[["Grade","Average"]])

In [28]:
df[["Grade","Average"]]

        Grade   Average
0    4.343805  4.290459
1    4.499810  4.330733
2    4.343805  4.025352
3    4.499810  4.442651
4    4.317488  3.970292
..        ...       ...
401  4.317488       NaN
402  4.304065  4.077537
403  4.465908       NaN
404  4.454347       NaN
405  4.394449  4.158883

[406 rows x 2 columns]

# **Encoding**

**Year, Gender and Scholarship**

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [30]:
df["Gender"] = le.fit_transform(df["Gender"])

In [31]:
df["Scholarship_Bulsary"] = le.fit_transform(df["Scholarship_Bulsary"])

In [32]:
df["Year"] = le.fit_transform(df["Year"])

In [33]:
df[["Year","Gender","Scholarship_Bulsary"]]

     Year  Gender  Scholarship_Bulsary
0       0       0                    0
1       0       1                    1
2       0       1                    0
3       0       1                    0
4       0       0                    0
..    ...     ...                  ...
401     0       0                    0
402     0       0                    1
403     0       0                    0
404     0       1                    0
405     0       0                    0

[406 rows x 3 columns]

In [34]:
df.columns

Index(['Gender', 'Grade', 'Year', 'Faculty', 'Average', 'Accomodation',
       'Monthly_Allowance', 'Scholarship_Bulsary', 'Study_Hours',
       'Class_Missed', 'Modules_Failed'],
      dtype='object')

**Faculty, Accomodation**

In [36]:
df = pd.get_dummies(df,columns = ["Faculty","Accomodation"])
df[["Faculty","Accomodation"]]

KeyError: "None of [Index(['Faculty', 'Accomodation'], dtype='object')] are in the [columns]"