# DAY 34
- Data Integration
- Encoding

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
    "acc": [1,2,3],
    "name": [0,9,8],
    "age":[3,5,7]
})

In [3]:
df1

   acc  name  age
0    1     0    3
1    2     9    5
2    3     8    7

In [5]:
df2 = pd.DataFrame({
    "acc": [1,24,33],
    "loan": [17,29,58],
})

In [7]:
concaticated = pd.concat([df1 , df2 ],axis=0)
concaticated

   acc  loan
0    1    17
1   24    29
2   33    58
0    1    17
1   24    29
2   33    58

In [10]:
concaticated_col = pd.concat([df1 , df2 ],axis=1)

In [11]:
concaticated_col

   acc  loan  acc  loan
0    1    17    1    17
1   24    29   24    29
2   33    58   33    58

In [13]:
# Merge ley 2 or more data frames

pd.merge(df1,df2 , how="inner", suffixes=("__left"  , "_right"))

   acc  loan
0    1    17
1   24    29
2   33    58

In [16]:
# join ley datafram join garauxa

df3 = pd.DataFrame({
    "key": [1,2,3],
    "name": [0,9,8],
    "age":[3,5,7]
})

df_3 = df3.set_index("key")
df_3

     name  age
key
1       0    3
2       9    5
3       8    7

In [ ]:
joined_df = df1.join(df3, how="right", lsuffix="_x")

In [18]:
joined_df

   acc  loan  key  name  age
0    1    17    1     0    3
1   24    29    2     9    5
2   33    58    3     8    7

In [19]:
df2.join(df1,how="right",rsuffix="_2")

   acc  loan  acc_2  loan_2
0    1    17      1      17
1   24    29     24      29
2   33    58     33      58

In [20]:
stacked_df = df1.stack()

In [21]:
stacked_df

0  acc      1
   loan    17
1  acc     24
   loan    29
2  acc     33
   loan    58
dtype: int64

In [24]:
unstacked_df = stacked_df.unstack()

In [25]:
unstacked_df

   acc  loan
0    1    17
1   24    29
2   33    58

In [26]:
titanic_df = pd.read_csv("titanic.csv")

In [27]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
titanic_df["Sex"] # <Nominal Data>

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [30]:
pd.get_dummies(titanic_df,  columns=["Sex"], dtype=int)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,1,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,1,0
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,0,1
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,0,1

In [31]:
pd.get_dummies(titanic_df,  columns=["Embarked"], dtype=int)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,0,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,0,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,1,0,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,0,1,0